- name: Gather only hardware-related facts
  ansible.builtin.setup:
    gather_subset:
      - hardware
- name: Calculate memory allocations
  set_fact:
    total_mem_mb: "{{ ansible_memtotal_mb | int }}"
    tomcat_memory_mb: "{{ (ansible_memtotal_mb * 0.5) | int }}"
    mysql_memory_mb: "{{ (ansible_memtotal_mb * 0.25) | int }}"
    php_memory_mb: "{{ (ansible_memtotal_mb * 0.10) | int }}"

- name: Format memory strings
  set_fact:
    tomcat_memory_str: "{{ tomcat_memory_mb }}m"
    mysql_memory_str: "{{ mysql_memory_mb }}M"
    php_memory_str: "{{ php_memory_mb }}m"

- name: Create .env file with calculated memory limits
  copy:
    dest: /app/docker/.env
    content: |
      TOMCAT_IMAGE={{ tomcat_image }}
      PHP_IMAGE={{ php_image }}
      MYSQL_IMAGE={{ mysql_image}}
      TOMCAT_MEMORY={{ tomcat_memory_str }}
      MYSQL_MEMORY={{ mysql_memory_str }}
      PHP_MEMORY={{ php_memory_str }}
    mode: '0644'
- name: Ensure the /app/services/mysql-8.0/config/ directory exists
  file:
    path: /app/services/mysql-8.0/config/
    state: directory
    mode: '0755'
- name: Update mysql folder with mysqld.cnf file
  template:
    src: containerized-services/mysql-8.0/mysqld.cnf.j2
    dest: /app/services/mysql-8.0/config/mysqld.cnf
    mode: '0644'
- name: Ensure the /app/services/php-8.3/ directory exists
  file:
    path: /app/services/php-8.3/
    state: directory
    mode: '0755'
- name: Copy PHP tar.gz archive
  ansible.builtin.copy:
    src: php-8.3.tar.gz   
    dest: /app/services/php-8.3.tar.gz           
    mode: '0644'
- name: Extract PHP folder from archive
  ansible.builtin.unarchive:
    src: /app/services/php-8.3.tar.gz
    dest: /app/services/
    remote_src: yes
    extra_opts: [--no-overwrite-dir]
- name: Ensure the /app/docker directory exists
  file:
    path: /app/docker
    state: directory
    mode: '0755'
- name: Update docker folder with docker-compose file
  template:
    src: containerized-services/docker-compose.yml.j2
    dest: /app/docker/docker-compose.yml
    mode: '0644'
- name: Bring up Docker Compose services
  command: docker compose -f /app/docker/docker-compose.yml up -d
- name: configure docker-compose service systemd files
  template:
    src: 'containerized-services/{{ item }}'
    dest: /etc/systemd/system/
  with_items:
    - docker-compose.service
- name: setting permissions for systemd services
  file:
    dest: '/etc/systemd/system/{{ item }}'
    owner: root
    group: root
    mode: 'u=rwX,g=rX,o=rX'
  with_items:
    - docker-compose.service
- name: Restart docker-compose service (with daemon reload)
  systemd:
    name: '{{ item }}'
    state: started
    daemon_reload: 'yes'
    enabled: 'yes'
  with_items:
    - docker-compose.service




